<!--
Date: April 17, 2025
Purpose: SwiftLint configuration file for CareSupport iOS app
Contains: Rule specifications for enforcing consistent Swift code style
-->

# Default rules are enabled by default.
# See: https://realm.github.io/SwiftLint/rule-directory.html

# Disabled rules
disabled_rules:
  - trailing_whitespace
  - todo
  - cyclomatic_complexity

# Opt-in rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - empty_count
  - empty_string
  - explicit_init
  - explicit_self
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicit_return
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - strict_fileprivate
  - toggle_bool
  - unowned_variable_capture
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

# Customized rules
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

identifier_name:
  min_length: 2
  excluded:
    - id
    - URL
    - x
    - y
    - to
    - in
    - at
    - vm

type_name:
  min_length: 3
  max_length: 50

function_parameter_count:
  warning: 6
  error: 8

file_length:
  warning: 500
  error: 1000

nesting:
  type_level:
    warning: 3
  statement_level:
    warning: 5

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 500

included:
  - CareSupport
excluded:
  - Carthage
  - Pods
  - CareSupport/Generated
  - CareSupport/Resources
  - fastlane
  - vendor

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging, summary)
